import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { NavMobile } from "../components/layout/NavMobile";

const onestFont = Onest({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "App Gestion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onestFont.className} antialiased bg-neutral-100`}
      >
        <nav>
          <NavMobile></NavMobile>
        </nav>
        <main className="p-2.5 h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
